export { hasAnyOfAttributes } from './hasAnyOfAttributes'
export { hasJustOneLinebreak } from './hasJustOneLinebreak'
export { hasOnlyLinebreaks } from './hasOnlyLinebreaks'
export { isBlock } from './isBlock'
export { isEmpty } from './isEmpty'
export { isHeading } from './isHeading'
export { isNotEmpty } from './isNotEmpty'
